### ISSUE TITLE
In none-tty console, process.stdout.clearLine is not a function

### ISSUE THREAD

**Issue by dancon** [crimson-med/Crimson-ProgressBar#1]
# **Information:**

none-tty console, `process.stdout.clearLine` and `process.stdout.cursorTo` is not a function.

**Version:** 

`1.2.0`

**Type:** 

`Render Error`

**Code:** 

```js
const crimsonProgressBar = require("crimson-progressbar");
crimsonProgressBar.renderProgressBar(50, 100, "red", "grey", "-", "==");
```

# **Problem:** 

Maybe you should use readline nodejs module.

> Describe your problem here

**Comment by dancon** [comment]
I've commit a pull request #2

**Comment by crimson-med** [comment]
@dancon merged and updated the package on npm and on github. Thanks for the tip!
